import random

DEFAULTS = {
    "subject": (
        "a tatsii woman, dark wavy hair loose, standing with arms relaxed at her sides, expression calm and self-possessed\n"
        "a tatsii woman, sitting cross-legged, hair falling over one shoulder, hands resting lightly in her lap\n"
        "a tatsii woman, leaning forward on her elbows, dark eyes intent, wavy hair framing her face\n"
        "a tatsii woman, crouching low, weight balanced on her heels, hair tumbling forward\n"
        "a tatsii woman, standing with one hand on her hip, chin lifted, wavy dark hair swept back\n"
        "a tatsii woman, perched on the edge of a surface, legs dangling, expression quietly amused\n"
        "a tatsii woman, lying on her stomach, chin propped on both hands, dark hair fanned around her\n"
        "a tatsii woman, kneeling upright, posture straight, wavy hair loose down her back\n"
        "a tatsii woman, standing with arms crossed loosely, dark wavy hair slightly wind-tossed\n"
        "a tatsii woman, sitting sideways, one knee drawn up, looking slightly to the side\n"
        "a tatsii woman, stretching her arms overhead, wavy dark hair shifting with the movement\n"
        "a tatsii woman, leaning against something with one shoulder, expression wry and knowing\n"
        "a tatsii woman, reclining on her back, hair spread out, one arm folded under her head\n"
        "a tatsii woman, sitting on her heels, hands folded in her lap, expression soft and pensive\n"
        "a tatsii woman, standing feet apart, arms loosely open, dark wavy hair voluminous and free\n"
        "a tatsii woman, bent slightly at the waist, hands on her knees, hair falling forward in waves\n"
        "a tatsii woman, lying on her side, one hand tucked under her cheek, expression languid\n"
        "a tatsii woman, standing with one foot slightly forward, weight shifted, relaxed confidence in her posture\n"
        "a tatsii woman, seated with legs stretched out in front, leaning back on both palms\n"
        "a tatsii woman, crouching with arms wrapped around her knees, dark hair coiling over her shoulders\n"
        "a tatsii woman, tilting her head to one side, wavy hair sliding off her shoulder\n"
        "a tatsii woman, standing tall, chin level, dark eyes steady, hair resting thick on her back\n"
        "a tatsii woman, kneeling with one knee raised, elbow on that knee, chin resting on her fist\n"
        "a tatsii woman, sitting with legs folded to one side, posture easy and unhurried\n"
        "a tatsii woman, twisting at the torso, dark wavy hair fanning with the motion\n"
        "a tatsii woman, lying on her back with one arm stretched above her head, expression dreamy\n"
        "a tatsii woman, leaning back in a seat, one ankle crossed over the other knee, relaxed\n"
        "a tatsii woman, standing with fingers loosely interlaced in front of her, expression composed\n"
        "a tatsii woman, stooping to pick something up, wavy dark hair cascading forward\n"
        "a tatsii woman, seated on the floor, back against her knees, arms wrapped around her legs\n"
        "a tatsii woman, standing on the balls of her feet, chin raised, dark wavy hair buoyant\n"
        "a tatsii woman, sitting up straight with hands clasped on her lap, expression attentive\n"
        "a tatsii woman, reclining against a surface, one leg bent, the other stretched, posture effortless\n"
        "a tatsii woman, half-kneeling, one hand flat on the ground, dark hair grazing the floor\n"
        "a tatsii woman, leaning back with arms behind her, fingers splayed against a surface, head tipped back slightly\n"
        "a tatsii woman, standing with one arm raised and elbow bent, touching the back of her neck\n"
        "a tatsii woman, curled on her side, knees drawn up, wavy hair tucked around her face\n"
        "a tatsii woman, perched with ankles crossed and hands braced beside her hips, posture light\n"
        "a tatsii woman, sitting upright with one hand brushing hair from her face\n"
        "a tatsii woman, standing with shoulders slightly rolled forward, expression introspective and still\n"
        "a tatsii woman, crouching with one knee down, arms loosely dangling, dark wavy hair heavy\n"
        "a tatsii woman, lying face-up with both arms spread wide, hair fanned across the surface beneath her\n"
        "a tatsii woman, seated with one leg folded under her, elbow on the raised knee, chin in hand\n"
        "a tatsii woman, standing with her weight on one leg, opposite hip relaxed, arms loose\n"
        "a tatsii woman, kneeling with both hands pressed to the ground, wavy dark hair curtaining her face\n"
        "a tatsii woman, sitting with her back straight and hands on her thighs, expression direct and composed\n"
        "a tatsii woman, mid-turn on her feet, wavy hair sweeping with momentum, posture dynamic\n"
        "a tatsii woman, reclining fully, one arm draped across her midsection, eyes half-lidded\n"
        "a tatsii woman, standing with both hands raised to gather her wavy dark hair loosely\n"
        "a tatsii woman, seated on her knees, hands in her lap, dark eyes soft, expression unhurried"
    ),
    "action": (
        "reading a worn paperback in a crowded cafe\n"
        "stirring coffee absently while staring out a rain-streaked window\n"
        "pressing her palm flat against cold glass\n"
        "scrolling through old messages she keeps meaning to delete\n"
        "folding a paper crane from a receipt\n"
        "biting the end of a pen while thinking\n"
        "pulling a thread loose from her sleeve\n"
        "watching someone across the room without meaning to\n"
        "writing in the margins of a borrowed book\n"
        "holding a lit match until it almost burns her fingers\n"
        "braiding a friendship bracelet while listening to music\n"
        "typing fast on a laptop she keeps glancing away from\n"
        "pressing earbuds in deeper to block out noise\n"
        "sketching something quick on a napkin\n"
        "waiting for a train that is already late\n"
        "counting coins in her palm\n"
        "feeding pigeons from a paper bag\n"
        "trying on earrings in a shop mirror\n"
        "lacing up boots while sitting on a low wall\n"
        "tucking a note under someone else's door\n"
        "rolling up a map that won't stay flat\n"
        "pressing flowers between the pages of a journal\n"
        "humming along to a song no one else can hear\n"
        "adjusting a camera strap before lifting it\n"
        "blowing on soup that's still too hot\n"
        "peeling the label off a glass bottle\n"
        "chasing a receipt the wind just caught\n"
        "unlocking a bicycle outside a bookshop\n"
        "rereading the same line of a letter\n"
        "reaching up to grab something just out of reach\n"
        "practicing a word in another language under her breath\n"
        "laying out tarot cards slowly on a low table\n"
        "watching a candle burn down in a dark room\n"
        "playing the same guitar chord until it sounds right\n"
        "signing her name at the bottom of a long form\n"
        "arguing quietly on the phone in a hallway\n"
        "threading a needle in poor light\n"
        "wrapping something fragile in old newspaper\n"
        "sitting cross-legged on the floor sorting photographs\n"
        "pressing a stamp carefully onto an envelope\n"
        "pausing mid-sentence to find the right word\n"
        "watching a spider repair its web between two chairs\n"
        "losing a chess game she is still pretending to consider\n"
        "peeling wax from a finished candle with her thumbnail\n"
        "whispering something to a potted plant\n"
        "eating cherries and dropping the pits one by one\n"
        "fixing a hem with safety pins instead of thread\n"
        "tracing a route on a paper map with her finger\n"
        "tasting wine she has not decided she likes yet\n"
        "stepping off a bus into an unfamiliar street"
    ),
    "context": (
        "a Tokyo convenience store at midnight, shelves of neatly stacked onigiri and canned drinks behind, fluorescent light spilling across a linoleum floor\n"
        "a Moroccan riad courtyard in midday heat, terracotta tiles underfoot, a central fountain of carved stone, potted citrus trees along the whitewashed walls\n"
        "a Brooklyn rooftop in late summer, water towers and brick chimneys receding into the hazy skyline, a weathered wooden deck chair to the left\n"
        "a Scandinavian kitchen at dawn, pale birch cabinets and a soapstone counter, a ceramic pour-over and a linen dish towel draped over the sink edge\n"
        "a secondhand bookshop in Edinburgh, floor-to-ceiling shelves of paperbacks, a rolling library ladder, scattered receipts on a worn oak table\n"
        "a sun-bleached Greek island terrace overlooking the Aegean, whitewashed stone walls, blue-painted wooden shutters, a clay pot of dried herbs just out of frame\n"
        "a Paris atelier at dusk, bolts of silk and raw linen stacked against exposed stone walls, a dressmaker's form behind, chalk marks on the parquet floor\n"
        "a damp autumn forest in the Pacific Northwest, moss-covered basalt boulders, ferns pressing in from every side, fog threading between Douglas fir trunks\n"
        "a Sao Paulo market at noon, stalls of tropical fruit spilling across wooden tables, hand-lettered cardboard signs overhead, cobblestones slick from a recent rain\n"
        "a New York loft studio, raw concrete pillars, oversized factory windows with southern exposure, a drafting table buried under rolled blueprints to the right\n"
        "a Kyoto temple garden in early spring, raked gravel surrounding a central mossy stone, a wooden veranda just behind, cherry blossoms beginning to open overhead\n"
        "a Copenhagen cafe in November, steamed-up windows, a small round table with a matte-glazed cup and a folded newspaper, bentwood chairs all around\n"
        "an Athens flea market on a Sunday morning, bronze candlesticks and cracked ceramic plates spread across a cloth-covered trestle, a Byzantine icon leaning behind\n"
        "a Dublin pub interior at midday, dark mahogany bar top, brass tap handles, a glass of amber ale and a folded racing form on the counter\n"
        "a Montana meadow in midsummer, tall grass bending in the wind, a split-rail fence receding into the treeline, the Beartooth Range faint in the background\n"
        "a midcentury Palm Springs living room, low-slung rattan furniture, a terrazzo floor, a ceramic lamp and a stack of art books on the side table\n"
        "a Lisbon tram car in the afternoon, worn yellow leather seats, varnished wooden handrails, tiled buildings sliding past the scratched window glass\n"
        "a Vietnamese pho shop before opening, stacked plastic stools, broth simmering in a massive steel pot behind, bundles of rice noodles on a prep table\n"
        "a Berlin Neukoelln apartment in winter, bare plaster walls, a radiator hissing beneath a single-pane window, a pine table with an empty espresso cup\n"
        "a Havana courtyard in afternoon heat, crumbling ochre stucco walls, a rusted wrought-iron chair beneath a mango tree, laundry on a line overhead\n"
        "a Finnish lakeside sauna in July, rough-hewn pine benches, a bucket of water and a birch whisk on the floor, the still lake visible through the open door\n"
        "a London brutalist housing estate at dusk, raw concrete walkways, a rusted bicycle chained to a railing, the city lights beginning to appear in the distance\n"
        "a Nairobi flower market at dawn, buckets of protea and Bird-of-Paradise crowding the narrow aisle, wet concrete underfoot, corrugated metal walls behind\n"
        "a Buenos Aires milonga on a Saturday night, lacquered parquet floor, small tables draped in white linen around the edges, a bandoneon case open on a chair\n"
        "a Seoul banchan restaurant interior, white-tiled walls, small ceramic dishes of kimchi and pickled vegetables lined across a wooden table, chopstick rests beside each\n"
        "a Sicilian fishing village at sunrise, coiled ropes and wooden crates stacked on a salt-bleached dock, painted fishing boats bobbing just behind\n"
        "a Sydney beach at low tide in autumn, wet sand strewn with kelp, a lifeguard tower far behind, low surf breaking softly in the background\n"
        "a Portland coffee roastery, burlap sacks of green beans stacked against a whitewashed brick wall, a steel roasting drum in the background, chaff drifting in the air\n"
        "a Venetian canal-side in early morning, green water lapping at weathered travertine steps, a gondola moored to a barber-pole post to the left\n"
        "a Kyrgyz mountain camp in late summer, felt yurt panels behind, a copper kettle on a low wooden table, the high steppe visible through the open door\n"
        "a Barcelona bodega interior, shelves of dusty wine bottles floor to ceiling, terracotta floor tiles, a marble-topped bar with a small brass tap\n"
        "a New Orleans shotgun house interior, tin ceiling overhead, jalousie windows open to the street, a rocking chair with a woven cane seat just behind\n"
        "a Cape Town winelands estate in autumn, a crushed-gravel path between rows of dormant grapevines, a whitewashed Cape Dutch gable in the background\n"
        "a Chicago diner at 3 a.m., laminate counter in mint green, chrome bar stools, a pie case glowing behind the pass-through to the kitchen\n"
        "a Tallinn medieval street in winter, snow packed between cobblestones, limestone guild hall walls on both sides, an iron lantern hanging overhead\n"
        "a Marrakech souk corridor at midday, shafts of light through a cane lattice roof, stacked brassware and patterned kilims lining both sides of the narrow lane\n"
        "a Tokyo kissaten in afternoon, dark wood paneling, a vintage record player on a corner shelf, ceramic cups and a small glass sugar dispenser on each table\n"
        "an Atacama desert at dusk, terracotta earth stretching to a volcanic ridge, a single adobe shelter behind, the sky shifting from orange to deep violet\n"
        "a Montreal Mile End apartment in autumn, original fir floors, a cast-iron radiator by tall sash windows, stacks of vinyl records on a plywood shelf\n"
        "a Balinese rice paddy at dawn, tiered emerald terraces receding up a hillside, bamboo irrigation flutes trickling in the background, morning mist across the valley\n"
        "a Swiss Alpine hut in early spring, rough stone walls, a pine-plank table with a ceramic jug, snow still covering the meadow visible through a small window\n"
        "a Havana Malecon at dusk, the sea wall crumbling behind, the ocean grey-green beyond, old American cars rolling past on the broad avenue\n"
        "an Istanbul Grand Bazaar interior, vaulted stone ceiling, lanterns hanging at intervals, bolts of embroidered fabric stacked against a recessed archway to the right\n"
        "a remote Iceland beach in autumn, black volcanic sand stretching in both directions, basalt columns rising behind, the Atlantic crashing in the background\n"
        "an Oaxacan market courtyard, metate stone and clay comals arranged on low tables, woven palm baskets overhead, a bougainvillea-covered adobe wall behind\n"
        "a Penang shophouse interior, original encaustic tile floor in geometric patterns, a hand-painted enamel sign leaning against peeling colonial plaster, rattan blinds half-drawn\n"
        "a rural Tuscany kitchen in August, a rough terracotta crock of dried porcini on a shelf, braided garlic overhead, a pine farmhouse table with scattered flour\n"
        "an Amsterdam canal apartment in winter, original timber ceiling beams, a cast-iron stove in the corner, canal boats visible through tall paned windows behind\n"
        "a Manila jeepney interior, chrome rails and mirrored panels overhead, painted saints along the front fascia, the street a blur of neon through the open back\n"
        "a Jordanian desert camp at night, hand-knotted wool rugs spread across the sand, a brass tea set on a low cedar table, the Milky Way overhead"
    ),
    "lighting": (
        "soft overcast daylight from a north-facing window, even and shadowless, rendering cool whites across all surfaces\n"
        "a bare tungsten bulb hanging at center frame, warm amber pool below, darkness bleeding in from every edge\n"
        "harsh midday sun from directly overhead, bleaching highlights and crushing shadows beneath the chin and brow\n"
        "fluorescent strip lights on the ceiling, flat and clinical, a faint green cast across skin and walls\n"
        "single candle held close and below, warm orange light dancing upward, shadows shifting with each flicker\n"
        "rim light from behind and above, cold white LED, separating subject from a deep unlit background\n"
        "low-pressure sodium streetlamp from the right, a narrow band of sickly amber against blue-black shadow\n"
        "two strip softboxes flanking from the sides, warm white, fill nearly matching the key, almost shadowless\n"
        "bounced flash off a white ceiling overhead, soft and directionless, flat natural-looking color temperature\n"
        "morning fog light, soft and low from the east, barely directional, pale grey with a faint lavender undertone\n"
        "practical desk lamp to the lower left, tungsten warm, casting an upward wash that fades before reaching the ceiling\n"
        "blue-hour skylight from above through a skylight, deeply desaturated, cool and still, long soft gradients\n"
        "kino flo bank at forty-five degrees from the left, daylight-balanced, smooth soft gradients across the form\n"
        "a grid-spotted fresnel from high camera right, tight beam, hard-edged shadow angling across to the left\n"
        "neon sign off-camera right, saturated magenta, mixing with cooler ambient from the window opposite\n"
        "harsh direct flash on-axis, flat and airless, slight blue cast from a bare speedlight at full power\n"
        "canopy of bare incandescent bulbs overhead, warm layered light from multiple directions, shallow falloff\n"
        "car headlights from the front, hard twin beams cutting through, deep shadow behind the subject\n"
        "practicals in the background glowing amber while the foreground receives cool blue fill from above\n"
        "a ringflash mounted on-axis, perfectly even, shadow wrapping around the subject edge all the way around\n"
        "moonlight from high camera left, blue-cool, hard-edged shadow falling sharply to the right, minimal fill\n"
        "large parabolic softbox overhead and slightly forward, neutral daylight, smooth gradient from crown to chin\n"
        "LED panel cold from the right, crossed by warm bounce from a silver reflector left and below\n"
        "campfire below and in front, orange warm light fluctuating, rimming from above with cooler night sky\n"
        "fog-filtered sun from behind, a diffuse backlight glow, subject almost silhouetted, light wrapping the edges\n"
        "a single practical lantern stage right, orange flicker, hard contrast against an otherwise dark space\n"
        "high-noon industrial skylight above, hard shafts of daylight, dust and scatter in the beam, deep flanking shadow\n"
        "aquarium glow from the left, blue-green cool light washing the near side, warm room bounce on the far side\n"
        "broad silk diffusion panel above and forward, daylight balanced, even soft light with a subtle downward direction\n"
        "single hair light from directly behind, pure white LED, strong separation, no other source in the scene\n"
        "warm sunset backlight from camera right, saturated orange, long shadow angling left, slight rim on the shoulder\n"
        "overhead grid softbox on a shoot-through, two stops above ambient, neutral, clean downward gradient\n"
        "bare flash with a thin grid from forty-five degrees right, tight falloff, warm gel added to balance tungsten ambient\n"
        "cool overcast sky from outside a window stage left, soft and directional enough to cast light shadows inward\n"
        "a practical TV screen off-camera, blue-white flickering light washing the left side of the subject intermittently\n"
        "under-lit from below by a light table or panel, cool white, reversing usual shadow direction up across the face\n"
        "daylight balanced LED panel backlit through a frosted shower door, even and soft, a flat fill from the side\n"
        "low-angle table lamp from the lower right, tungsten warm, light raking upward and catching texture on every surface\n"
        "mercury vapor industrial lamp overhead, green-tinted and harsh, hard shadows directly below, minimal ambient\n"
        "a strip of warm practical Christmas lights behind the subject, low-level orange glow filling the background plane\n"
        "softbox at head height directly in front, neutral 5500K, controlled and flat, slight fill from the floor bounce\n"
        "three-quarter backlight from upper camera left, hard LED, cool, a sharp highlight line across the far shoulder\n"
        "overcast winter light through bare branches, dappled and cool, moving slightly as wind shifts the canopy\n"
        "colored practicals in the background, deep red, while the foreground receives a cooler ambient daylight fill\n"
        "a follow-spot from above and behind, white, tight ellipse, the rest of the frame falling off to black quickly\n"
        "early morning diffuse light from a frosted east window, cool and low-angled, long soft shadows trailing left\n"
        "hard sidelight from camera left, a small reflector dish, creating split lighting with a bright side and dark side\n"
        "a single fire source below and in front, very warm deep orange, upward casting light, no ceiling bounce visible\n"
        "bounce light from a large silver reflector at ground level right, cold and hard enough to cast defined shadows upward\n"
        "dappled light through a louvered blind from the right, alternating warm bars of sunlight and cool shadow stripes"
    ),
        "style": 'editorial fashion photography, restrained and architectural, with a quiet-luxury feel\n1970s analog film aesthetic, slightly grainy with warm faded colors and a documentary mood\nhigh-contrast modern cinematography, desaturated with deep shadows and a tense moody atmosphere\nScandinavian minimalist photography, clean negative space, neutral palette, precise\nJapanese wabi-sabi photography, spare and asymmetric with a reverence for imperfection\nneon-soaked urban noir, rain-slicked surfaces and the moody palette of 1980s cinema\nDust Bowl documentary photography, gritty and compassionate in cool monochrome\nhigh-key commercial beauty photography, pristine whites and aspirational gloss\nautumnal French New Wave cinematography, natural light and a bittersweet intimate quality\nluxury watchmaking catalog aesthetic, obsessive macro precision and cool metallic depth\nraw street photography, candid and unposed with the grain of 35mm pushed film\ngolden-age Hollywood glamour photography, dramatic key light and velvety black shadows\nimmersive environmental portraiture in the style of New Color photography, deadpan and sharp\n1990s alternative music press photography, bleached and overexposed with a raw urgency\nluxe travel editorial, warm film tones and a languid sense of effortless sophistication\ncold conceptual art photography, detached and systematic with white-cube austerity\nsparse haiku-like photographic realism, one gesture, open space, and quiet attention\nsun-bleached Mediterranean documentary, bleached whites and terracotta warmth under harsh noon\ndreamlike pictorialist soft-focus, diffused light and a melancholic romantic atmosphere\nbrutalist architectural photography, severe geometry and raw texture in cold grey tones',
    "technical": (
        "tight close-up, eye level, facing the camera directly, shot on 85mm at f/1.4 with very shallow depth of field\n"
        "extreme close-up from slightly below, worm's eye angle, subject looking away, 100mm macro at f/2.8\n"
        "full-body shot, low angle, three-quarter view, 35mm at f/8 deep focus on Kodak Ektar 100\n"
        "medium shot, high angle, facing the camera directly, 50mm at f/4 on Fujifilm Superia 400\n"
        "cowboy shot, eye level, side profile, shot on 85mm at f/2 with soft background blur\n"
        "over-the-shoulder medium shot from behind and slightly above, 50mm at f/2.8 shallow depth of field\n"
        "wide shot, overhead top-down angle, subject facing away and small in frame, 24mm deep focus\n"
        "head-and-shoulders portrait, dutch tilt, three-quarter view, 85mm at f/1.8 on medium-format digital\n"
        "extreme wide shot, eye level, subject from behind in center of frame, 16mm at f/11 deep focus\n"
        "close-up, high angle, facing the camera directly, shot on 50mm at f/1.8 on Kodak Portra 800\n"
        "full-body shot, eye level, side profile, 35mm at f/5.6 deep focus on Ilford HP5\n"
        "cowboy shot, low angle, facing the camera directly, 85mm at f/2.8 shallow depth of field\n"
        "medium shot, worm's eye angle, three-quarter view, 35mm at f/4 on Kodak Portra 400\n"
        "head-and-shoulders portrait, eye level, looking away, 105mm at f/1.4 with extreme shallow depth of field\n"
        "wide environmental shot, high angle, subject small and in three-quarter view, 28mm at f/8 deep focus\n"
        "extreme close-up, eye level, three-quarter view, shot on 135mm at f/2 with creamy bokeh\n"
        "full-body shot, high angle, facing the camera directly, 24mm at f/7.1 on medium-format digital\n"
        "over-the-shoulder close-up from behind, eye level, 85mm at f/1.8 shallow depth of field\n"
        "medium shot, dutch tilt, side profile, 50mm at f/2.8 on Kodak Gold 200\n"
        "cowboy shot, high angle looking down, facing away, 35mm at f/5.6 on Fujifilm Pro 400H\n"
        "tight head-and-shoulders portrait, low angle, facing the camera directly, 85mm at f/2 on Kodak Portra 400\n"
        "wide shot, eye level, subject from behind and slightly to the side, 24mm at f/9 deep focus\n"
        "full-body shot, worm's eye angle, three-quarter view, 35mm at f/4 on CineStill 800T\n"
        "close-up, overhead top-down angle, facing the camera directly, 85mm at f/2.8 shallow depth of field\n"
        "medium shot, eye level, over-the-shoulder from slightly behind, 50mm at f/2 medium-format digital\n"
        "cowboy shot, dutch tilt, three-quarter view, 85mm at f/1.8 on Kodak Portra 160\n"
        "extreme wide shot, low angle, subject tiny and facing the camera directly, 14mm at f/11 deep focus\n"
        "head-and-shoulders portrait, high angle, looking away, 85mm at f/2.8 on Fujifilm Velvia 50\n"
        "full-body shot, eye level, from behind, 50mm at f/5.6 on Kodak Ektar 100\n"
        "medium shot, eye level, facing the camera directly, 85mm at f/1.4 with shallow depth of field on medium-format digital\n"
        "close-up, low angle, three-quarter view, 100mm at f/2 on Kodak Portra 800\n"
        "wide shot, high angle, subject in side profile at frame edge, 28mm at f/8 on CineStill 50D\n"
        "cowboy shot, eye level, from behind, 85mm at f/2.8 shallow depth of field\n"
        "extreme close-up, dutch tilt, facing the camera directly, 90mm at f/1.4 on medium-format digital\n"
        "full-body shot, high angle, looking away, 35mm at f/6.3 on Kodak Portra 400\n"
        "head-and-shoulders portrait, eye level, side profile, shot on 135mm at f/2 with very shallow depth of field\n"
        "medium shot, low angle, from behind, 50mm at f/4 deep focus on Ilford Delta 400\n"
        "over-the-shoulder wide shot, slightly above eye level, subject facing away into the distance, 35mm at f/5.6\n"
        "cowboy shot, worm's eye angle, facing the camera directly, 50mm at f/2.8 on Fujifilm Pro 400H\n"
        "tight close-up, high angle, three-quarter view, 85mm at f/1.8 on Kodak Portra 160\n"
        "extreme wide shot, eye level, subject in side profile at far left of frame, 21mm at f/10 deep focus\n"
        "full-body shot, dutch tilt, three-quarter view, 35mm at f/4 on CineStill 800T\n"
        "medium shot, overhead top-down angle, facing the camera directly, 50mm at f/2.8 medium-format digital\n"
        "head-and-shoulders portrait, low angle, from behind and slightly to the side, 85mm at f/2 shallow depth of field\n"
        "close-up, eye level, looking away, 100mm at f/2.8 on Kodak Portra 400\n"
        "cowboy shot, high angle, side profile, 85mm at f/1.8 on medium-format digital\n"
        "wide shot, low angle, subject facing the camera directly at center frame, 24mm at f/8 on Kodak Ektar 100\n"
        "full-body shot, eye level, three-quarter view, 50mm at f/4 on Fujifilm Superia 800\n"
        "extreme close-up, low angle, side profile, shot on 85mm at f/1.4 with shallow depth of field\n"
        "medium shot, eye level, facing the camera directly, 75mm at f/2.5 on Kodak Portra 400 medium-format"
    ),
}

def pick(opts_text, rng):
    lines = [l.strip() for l in opts_text.strip().splitlines() if l.strip()]
    return rng.choice(lines) if lines else ""

def build_prompts(subject, action, style, context, lighting, technical, seed, batch_size):
    # Klein canonical order: subject. action. context. lighting. style. camera.
    # Use parent RNG to derive well-distributed child seeds per batch item.
    parent = random.Random(seed)
    results = []
    for _ in range(batch_size):
        rng = random.Random(parent.randint(0, 2**31))
        parts = [pick(f, rng) for f in [subject, action, context, lighting, style, technical]]
        results.append(". ".join(p for p in parts if p))
    return results
